DROP TABLE IF EXISTS user;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    name TEXT UNIQUE NOT NULL,
    email TEXT NOT NULL UNIQUE, 
    profile_pic TEXT NOT NULL DEFAULT 'default.jpg',
)
